name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, intl, bcmath

    - name: Show PHP Version
      run: php -v

    - name: Show Composer Version
      run: composer -V

    - name: Increase Memory Limit
      run: echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    - name: Verify composer.json presence
      run: ls -la ${{ github.workspace }}/HappyCloud

    - name: Copy .env
      run: php -r "file_exists('HappyCloud/.env') || copy('HappyCloud/.env.example', 'HappyCloud/.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --working-dir=HappyCloud

    - name: Generate key
      run: php HappyCloud/artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 HappyCloud/storage HappyCloud/bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p HappyCloud/database
        touch HappyCloud/database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: HappyCloud/database/database.sqlite
      run: php HappyCloud/artisan test
