name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, intl, bcmath

    - name: Show PHP Version
      run: php -v

    - name: Show Composer Version
      run: composer -V

    - name: Copy .env
      run: php -r "file_exists('HappyCloud/.env') || copy('HappyCloud/.env.example', 'HappyCloud/.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --working-dir=HappyCloud

    - name: Generate key
      run: php HappyCloud/artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 HappyCloud/storage HappyCloud/bootstrap/cache

    - name: Update .env with DB credentials
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' HappyCloud/.env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' HappyCloud/.env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' HappyCloud/.env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel/' HappyCloud/.env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' HappyCloud/.env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' HappyCloud/.env

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php HappyCloud/artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php HappyCloud/artisan test
